name: pvp-toggle
version: '${project.version}'
main: com.lukeonuke.pvptoggle.PvpToggle
api-version: '1.20'
commands:
  pvp:
    description: "Toggle pvp"
    usage: /<command>
    permission: pvptoggle.pvp
permissions :
  pvptoggle.pvp.others:
    description: "Allows the player to toggle pvp of other players"
    default: op